version: "3.8"

services:
  app:
    container_name: backend_shopper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: arquivo
      DATABASE_URL: postgres://dev:dev@db:5432/app
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_shopper
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - "5432:5432"

volumes:
  db_data: